version: "3"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: tuvidb
      POSTGRES_USER: tuvidb
      POSTGRES_DB: tuvidb
    ports:
      - "5432:5432"

volumes:
  postgres-data:
